"use strict";
exports.__esModule = true;
var Bank;
(function (Bank) {
    Bank[Bank["American Express France"] = 0] = "American Express France";
    Bank[Bank["Ark\u00E9a Banque Priv\u00E9e"] = 1] = "Ark\u00E9a Banque Priv\u00E9e";
    Bank[Bank["AXA Banque"] = 2] = "AXA Banque";
    Bank[Bank["Banque BCP"] = 3] = "Banque BCP";
    Bank[Bank["Banque Casino"] = 4] = "Banque Casino";
    Bank[Bank["Banque Chalus"] = 5] = "Banque Chalus";
    Bank[Bank["Banque Courtois"] = 6] = "Banque Courtois";
    Bank[Bank["Banque de la R\u00E9union"] = 7] = "Banque de la R\u00E9union";
    Bank[Bank["Banque De Savoie"] = 8] = "Banque De Savoie";
    Bank[Bank["Banque Kolb"] = 9] = "Banque Kolb";
    Bank[Bank["Banque Laydernier"] = 10] = "Banque Laydernier";
    Bank[Bank["Banque Nuger"] = 11] = "Banque Nuger";
    Bank[Bank["Banque Palatine Particuliers"] = 12] = "Banque Palatine Particuliers";
    Bank[Bank["Banque Palatine - Entreprises & Prof. Immobili\u00E8res"] = 13] = "Banque Palatine - Entreprises & Prof. Immobili\u00E8res";
    Bank[Bank["Banque Populaire Alsace Lorraine Champagne"] = 14] = "Banque Populaire Alsace Lorraine Champagne";
    Bank[Bank["Banque Populaire Aquitaine Centre Atlantique"] = 15] = "Banque Populaire Aquitaine Centre Atlantique";
    Bank[Bank["Banque Populaire Atlantique"] = 16] = "Banque Populaire Atlantique";
    Bank[Bank["Banque Populaire Bourgogne Franche-Comt\u00E9"] = 17] = "Banque Populaire Bourgogne Franche-Comt\u00E9";
    Bank[Bank["Banque Populaire de l'Ouest"] = 18] = "Banque Populaire de l'Ouest";
    Bank[Bank["Banque Populaire des Alpes"] = 19] = "Banque Populaire des Alpes";
    Bank[Bank["Banque Populaire du Massif Central"] = 20] = "Banque Populaire du Massif Central";
    Bank[Bank["Banque Populaire du Nord"] = 21] = "Banque Populaire du Nord";
    Bank[Bank["Banque Populaire du Sud"] = 22] = "Banque Populaire du Sud";
    Bank[Bank["Banque Populaire Loire et Lyonnais"] = 23] = "Banque Populaire Loire et Lyonnais";
    Bank[Bank["Banque Populaire M\u00E9diterran\u00E9e"] = 24] = "Banque Populaire M\u00E9diterran\u00E9e";
    Bank[Bank["Banque Populaire Occitane"] = 25] = "Banque Populaire Occitane";
    Bank[Bank["Banque Populaire Rives de Paris"] = 26] = "Banque Populaire Rives de Paris";
    Bank[Bank["Banque Populaire Val de France"] = 27] = "Banque Populaire Val de France";
    Bank[Bank["Banque Rh\u00F4ne-Alpes"] = 28] = "Banque Rh\u00F4ne-Alpes";
    Bank[Bank["Banque SBE"] = 29] = "Banque SBE";
    Bank[Bank["Banque Tarneaud"] = 30] = "Banque Tarneaud";
    Bank[Bank["BforBank"] = 31] = "BforBank";
    Bank[Bank["BNP Paribas Particuliers"] = 32] = "BNP Paribas Particuliers";
    Bank[Bank["BNP Priv\u00E9e"] = 33] = "BNP Priv\u00E9e";
    Bank[Bank["BNP Paribas Pro"] = 34] = "BNP Paribas Pro";
    Bank[Bank["BNP Net Entreprises"] = 35] = "BNP Net Entreprises";
    Bank[Bank["BNP Net Entreprises (Lecteur sans fil)"] = 36] = "BNP Net Entreprises (Lecteur sans fil)";
    Bank[Bank["BNP Guadeloupe"] = 37] = "BNP Guadeloupe";
    Bank[Bank["BNP Guyane"] = 38] = "BNP Guyane";
    Bank[Bank["BNP Martinique"] = 39] = "BNP Martinique";
    Bank[Bank["BNP R\u00E9union"] = 40] = "BNP R\u00E9union";
    Bank[Bank["Boursorama"] = 41] = "Boursorama";
    Bank[Bank["Bred"] = 42] = "Bred";
    Bank[Bank["Bred Pro"] = 43] = "Bred Pro";
    Bank[Bank["Caisse d'Epargne Particuliers"] = 44] = "Caisse d'Epargne Particuliers";
    Bank[Bank["Caisse d'Epargne Pro "] = 45] = "Caisse d'Epargne Pro ";
    Bank[Bank["Caisse d'Epargne Entreprises (CENET)"] = 46] = "Caisse d'Epargne Entreprises (CENET)";
    Bank[Bank["Carrefour Banque"] = 47] = "Carrefour Banque";
    Bank[Bank["CIC"] = 48] = "CIC";
    Bank[Bank["Compte Nickel"] = 49] = "Compte Nickel";
    Bank[Bank["Cr\u00E9dit Agricole Alpes Provence"] = 50] = "Cr\u00E9dit Agricole Alpes Provence";
    Bank[Bank["Cr\u00E9dit Agricole Alsace Vosges"] = 51] = "Cr\u00E9dit Agricole Alsace Vosges";
    Bank[Bank["Cr\u00E9dit Agricole Anjou Maine"] = 52] = "Cr\u00E9dit Agricole Anjou Maine";
    Bank[Bank["Cr\u00E9dit Agricole Aquitaine"] = 53] = "Cr\u00E9dit Agricole Aquitaine";
    Bank[Bank["Cr\u00E9dit Agricole Atlantique Vend\u00E9e"] = 54] = "Cr\u00E9dit Agricole Atlantique Vend\u00E9e";
    Bank[Bank["Cr\u00E9dit Agricole Brie Picardie"] = 55] = "Cr\u00E9dit Agricole Brie Picardie";
    Bank[Bank["Cr\u00E9dit Agricole Centre France"] = 56] = "Cr\u00E9dit Agricole Centre France";
    Bank[Bank["Cr\u00E9dit Agricole Centre Loire"] = 57] = "Cr\u00E9dit Agricole Centre Loire";
    Bank[Bank["Cr\u00E9dit Agricole Centre-Est"] = 58] = "Cr\u00E9dit Agricole Centre-Est";
    Bank[Bank["Cr\u00E9dit Agricole Centre-Ouest"] = 59] = "Cr\u00E9dit Agricole Centre-Ouest";
    Bank[Bank["Cr\u00E9dit Agricole Champagne-Bourgogne"] = 60] = "Cr\u00E9dit Agricole Champagne-Bourgogne";
    Bank[Bank["Cr\u00E9dit Agricole Charente P\u00E9rigord"] = 61] = "Cr\u00E9dit Agricole Charente P\u00E9rigord";
    Bank[Bank["Cr\u00E9dit Agricole Charente-Maritime"] = 62] = "Cr\u00E9dit Agricole Charente-Maritime";
    Bank[Bank["Cr\u00E9dit Agricole Corse"] = 63] = "Cr\u00E9dit Agricole Corse";
    Bank[Bank["Cr\u00E9dit Agricole C\u00F4tes d'Armor"] = 64] = "Cr\u00E9dit Agricole C\u00F4tes d'Armor";
    Bank[Bank["Cr\u00E9dit Agricole Deux-S\u00E8vres"] = 65] = "Cr\u00E9dit Agricole Deux-S\u00E8vres";
    Bank[Bank["Cr\u00E9dit Agricole Finist\u00E8re"] = 66] = "Cr\u00E9dit Agricole Finist\u00E8re";
    Bank[Bank["Cr\u00E9dit Agricole Franche Comt\u00E9"] = 67] = "Cr\u00E9dit Agricole Franche Comt\u00E9";
    Bank[Bank["Cr\u00E9dit Agricole Guadeloupe"] = 68] = "Cr\u00E9dit Agricole Guadeloupe";
    Bank[Bank["Cr\u00E9dit Agricole Ile de France"] = 69] = "Cr\u00E9dit Agricole Ile de France";
    Bank[Bank["Cr\u00E9dit Agricole Ille-et-Vilaine"] = 70] = "Cr\u00E9dit Agricole Ille-et-Vilaine";
    Bank[Bank["Cr\u00E9dit Agricole Languedoc"] = 71] = "Cr\u00E9dit Agricole Languedoc";
    Bank[Bank["Cr\u00E9dit Agricole Loire Haute Loire"] = 72] = "Cr\u00E9dit Agricole Loire Haute Loire";
    Bank[Bank["Cr\u00E9dit Agricole Lorraine"] = 73] = "Cr\u00E9dit Agricole Lorraine";
    Bank[Bank["Cr\u00E9dit Agricole Martinique-Guyane"] = 74] = "Cr\u00E9dit Agricole Martinique-Guyane";
    Bank[Bank["Cr\u00E9dit Agricole Morbihan"] = 75] = "Cr\u00E9dit Agricole Morbihan";
    Bank[Bank["Cr\u00E9dit Agricole Nord De France"] = 76] = "Cr\u00E9dit Agricole Nord De France";
    Bank[Bank["Cr\u00E9dit Agricole Nord Est"] = 77] = "Cr\u00E9dit Agricole Nord Est";
    Bank[Bank["Cr\u00E9dit Agricole Nord Midi-Pyr\u00E9n\u00E9es"] = 78] = "Cr\u00E9dit Agricole Nord Midi-Pyr\u00E9n\u00E9es";
    Bank[Bank["Cr\u00E9dit Agricole Normandie"] = 79] = "Cr\u00E9dit Agricole Normandie";
    Bank[Bank["Cr\u00E9dit Agricole Normandie Seine"] = 80] = "Cr\u00E9dit Agricole Normandie Seine";
    Bank[Bank["Cr\u00E9dit Agricole Provence C\u00F4te d'Azu"] = 81] = "Cr\u00E9dit Agricole Provence C\u00F4te d'Azu";
    Bank[Bank["Cr\u00E9dit Agricole Pyr\u00E9n\u00E9es Gascogne"] = 82] = "Cr\u00E9dit Agricole Pyr\u00E9n\u00E9es Gascogne";
    Bank[Bank["Cr\u00E9dit Agricole R\u00E9union"] = 83] = "Cr\u00E9dit Agricole R\u00E9union";
    Bank[Bank["Cr\u00E9dit Agricole Savoie"] = 84] = "Cr\u00E9dit Agricole Savoie";
    Bank[Bank["Cr\u00E9dit Agricole Sud M\u00E9diterran\u00E9e"] = 85] = "Cr\u00E9dit Agricole Sud M\u00E9diterran\u00E9e";
    Bank[Bank["Cr\u00E9dit Agricole Sud Rh\u00F4ne Alpes"] = 86] = "Cr\u00E9dit Agricole Sud Rh\u00F4ne Alpes";
    Bank[Bank["Cr\u00E9dit Agricole Toulouse 31"] = 87] = "Cr\u00E9dit Agricole Toulouse 31";
    Bank[Bank["Cr\u00E9dit Agricole Touraine Poitou"] = 88] = "Cr\u00E9dit Agricole Touraine Poitou";
    Bank[Bank["Cr\u00E9dit Agricole Val de France"] = 89] = "Cr\u00E9dit Agricole Val de France";
    Bank[Bank["Cr\u00E9dit Coop\u00E9ratif"] = 90] = "Cr\u00E9dit Coop\u00E9ratif";
    Bank[Bank["Cr\u00E9dit du Nord"] = 91] = "Cr\u00E9dit du Nord";
    Bank[Bank["Cr\u00E9dit Maritime Atlantique"] = 92] = "Cr\u00E9dit Maritime Atlantique";
    Bank[Bank["Cr\u00E9dit Maritime Bretagne-Normandie"] = 93] = "Cr\u00E9dit Maritime Bretagne-Normandie";
    Bank[Bank["Cr\u00E9dit Maritime de la R\u00E9gion Nord"] = 94] = "Cr\u00E9dit Maritime de la R\u00E9gion Nord";
    Bank[Bank["Cr\u00E9dit Maritime du Littoral du Sud-Ouest"] = 95] = "Cr\u00E9dit Maritime du Littoral du Sud-Ouest";
    Bank[Bank["Cr\u00E9dit Mutuel - Site National"] = 96] = "Cr\u00E9dit Mutuel - Site National";
    Bank[Bank["Cr\u00E9dit Mutuel Antilles-Guyane"] = 97] = "Cr\u00E9dit Mutuel Antilles-Guyane";
    Bank[Bank["Cr\u00E9dit Mutuel de Bretagne"] = 98] = "Cr\u00E9dit Mutuel de Bretagne";
    Bank[Bank["Cr\u00E9dit Mutuel de Bretagne Pro"] = 99] = "Cr\u00E9dit Mutuel de Bretagne Pro";
    Bank[Bank["Cr\u00E9dit Mutuel du Sud-Ouest"] = 100] = "Cr\u00E9dit Mutuel du Sud-Ouest";
    Bank[Bank["Cr\u00E9dit Mutuel du Sud-Ouest Pro"] = 101] = "Cr\u00E9dit Mutuel du Sud-Ouest Pro";
    Bank[Bank["Cr\u00E9dit Mutuel Maine-Anjou"] = 102] = "Cr\u00E9dit Mutuel Maine-Anjou";
    Bank[Bank["Cr\u00E9dit Mutuel Massif Central"] = 103] = "Cr\u00E9dit Mutuel Massif Central";
    Bank[Bank["Cr\u00E9dit Mutuel Massif Central Pro"] = 104] = "Cr\u00E9dit Mutuel Massif Central Pro";
    Bank[Bank["Cr\u00E9dit Mutuel Nord-Europe"] = 105] = "Cr\u00E9dit Mutuel Nord-Europe";
    Bank[Bank["Cr\u00E9dit Mutuel Oc\u00E9an"] = 106] = "Cr\u00E9dit Mutuel Oc\u00E9an";
    Bank[Bank["Czam"] = 107] = "Czam";
    Bank[Bank["DispoBank"] = 108] = "DispoBank";
    Bank[Bank["Fortuneo"] = 109] = "Fortuneo";
    Bank[Bank["Groupama Banque"] = 110] = "Groupama Banque";
    Bank[Bank["Hello Bank"] = 111] = "Hello Bank";
    Bank[Bank["HSBC France"] = 112] = "HSBC France";
    Bank[Bank["HSBC France Pro"] = 113] = "HSBC France Pro";
    Bank[Bank["HSBC Entreprise (Elys PC)"] = 114] = "HSBC Entreprise (Elys PC)";
    Bank[Bank["HSBC Professionnel (Elys PC)"] = 115] = "HSBC Professionnel (Elys PC)";
    Bank[Bank["ING"] = 116] = "ING";
    Bank[Bank["La Banque Postale Particuliers"] = 117] = "La Banque Postale Particuliers";
    Bank[Bank["La Banque Postale Pro"] = 118] = "La Banque Postale Pro";
    Bank[Bank["LCL"] = 119] = "LCL";
    Bank[Bank["LCL - e.LCL, 100% en ligne"] = 120] = "LCL - e.LCL, 100% en ligne";
    Bank[Bank["LCL Entreprises et institutionnels"] = 121] = "LCL Entreprises et institutionnels";
    Bank[Bank["LCL Pro"] = 122] = "LCL Pro";
    Bank[Bank["Milleis"] = 123] = "Milleis";
    Bank[Bank["Monabanq"] = 124] = "Monabanq";
    Bank[Bank["N26 (Number 26)"] = 125] = "N26 (Number 26)";
    Bank[Bank["Natixis"] = 126] = "Natixis";
    Bank[Bank["Oney - Banque Accord"] = 127] = "Oney - Banque Accord";
    Bank[Bank["Oney Banque"] = 128] = "Oney Banque";
    Bank[Bank["Orange Bank"] = 129] = "Orange Bank";
    Bank[Bank["PayPal"] = 130] = "PayPal";
    Bank[Bank["Qonto"] = 131] = "Qonto";
    Bank[Bank["Revolut"] = 132] = "Revolut";
    Bank[Bank["Shine"] = 133] = "Shine";
    Bank[Bank["Soci\u00E9t\u00E9 G\u00E9n\u00E9rale Entreprises"] = 134] = "Soci\u00E9t\u00E9 G\u00E9n\u00E9rale Entreprises";
    Bank[Bank["Soci\u00E9t\u00E9 G\u00E9n\u00E9rale Particuliers"] = 135] = "Soci\u00E9t\u00E9 G\u00E9n\u00E9rale Particuliers";
    Bank[Bank["Soci\u00E9t\u00E9 G\u00E9n\u00E9rale Pro"] = 136] = "Soci\u00E9t\u00E9 G\u00E9n\u00E9rale Pro";
    Bank[Bank["Soci\u00E9t\u00E9 Marseillaise de Cr\u00E9dit"] = 137] = "Soci\u00E9t\u00E9 Marseillaise de Cr\u00E9dit";
    Bank[Bank["Unilend"] = 138] = "Unilend";
    Bank[Bank["Yomoni"] = 139] = "Yomoni";
})(Bank = exports.Bank || (exports.Bank = {}));
