export enum Bank {
"American Express France",
"Arkéa Banque Privée",
"AXA Banque",
"Banque BCP",
"Banque Casino",
"Banque Chalus",
"Banque Courtois",
"Banque de la Réunion",
"Banque De Savoie",
"Banque Kolb",
"Banque Laydernier",
"Banque Nuger",
"Banque Palatine Particuliers",
"Banque Palatine - Entreprises & Prof. Immobilières",
"Banque Populaire Alsace Lorraine Champagne",
"Banque Populaire Aquitaine Centre Atlantique",
"Banque Populaire Atlantique",
"Banque Populaire Bourgogne Franche-Comté",
"Banque Populaire de l'Ouest",
"Banque Populaire des Alpes",
"Banque Populaire du Massif Central",
"Banque Populaire du Nord",
"Banque Populaire du Sud",
"Banque Populaire Loire et Lyonnais",
"Banque Populaire Méditerranée",
"Banque Populaire Occitane",
"Banque Populaire Rives de Paris",
"Banque Populaire Val de France",
"Banque Rhône-Alpes",
"Banque SBE",
"Banque Tarneaud",
"BforBank",
"BNP Paribas Particuliers",
"BNP Privée",
"BNP Paribas Pro",
"BNP Net Entreprises",
"BNP Net Entreprises (Lecteur sans fil)",
"BNP Guadeloupe",
"BNP Guyane",
"BNP Martinique",
"BNP Réunion",
"Boursorama",
"Bred",
"Bred Pro",
"Caisse d'Epargne Particuliers",
"Caisse d'Epargne Pro ",
"Caisse d'Epargne Entreprises (CENET)",
"Carrefour Banque",
"CIC",
"Compte Nickel",
"Crédit Agricole Alpes Provence",
"Crédit Agricole Alsace Vosges",
"Crédit Agricole Anjou Maine",
"Crédit Agricole Aquitaine",
"Crédit Agricole Atlantique Vendée",
"Crédit Agricole Brie Picardie",
"Crédit Agricole Centre France",
"Crédit Agricole Centre Loire",
"Crédit Agricole Centre-Est",
"Crédit Agricole Centre-Ouest",
"Crédit Agricole Champagne-Bourgogne",
"Crédit Agricole Charente Périgord",
"Crédit Agricole Charente-Maritime",
"Crédit Agricole Corse",
"Crédit Agricole Côtes d'Armor",
"Crédit Agricole Deux-Sèvres",
"Crédit Agricole Finistère",
"Crédit Agricole Franche Comté",
"Crédit Agricole Guadeloupe",
"Crédit Agricole Ile de France",
"Crédit Agricole Ille-et-Vilaine",
"Crédit Agricole Languedoc",
"Crédit Agricole Loire Haute Loire",
"Crédit Agricole Lorraine",
"Crédit Agricole Martinique-Guyane",
"Crédit Agricole Morbihan",
"Crédit Agricole Nord De France",
"Crédit Agricole Nord Est",
"Crédit Agricole Nord Midi-Pyrénées",
"Crédit Agricole Normandie",
"Crédit Agricole Normandie Seine",
"Crédit Agricole Provence Côte d'Azu",
"Crédit Agricole Pyrénées Gascogne",
"Crédit Agricole Réunion",
"Crédit Agricole Savoie",
"Crédit Agricole Sud Méditerranée",
"Crédit Agricole Sud Rhône Alpes",
"Crédit Agricole Toulouse 31",
"Crédit Agricole Touraine Poitou",
"Crédit Agricole Val de France",
"Crédit Coopératif",
"Crédit du Nord",
"Crédit Maritime Atlantique",
"Crédit Maritime Bretagne-Normandie",
"Crédit Maritime de la Région Nord",
"Crédit Maritime du Littoral du Sud-Ouest",
"Crédit Mutuel - Site National",
"Crédit Mutuel Antilles-Guyane",
"Crédit Mutuel de Bretagne",
"Crédit Mutuel de Bretagne Pro",
"Crédit Mutuel du Sud-Ouest",
"Crédit Mutuel du Sud-Ouest Pro",
"Crédit Mutuel Maine-Anjou",
"Crédit Mutuel Massif Central",
"Crédit Mutuel Massif Central Pro",
"Crédit Mutuel Nord-Europe",
"Crédit Mutuel Océan",
"Czam",
"DispoBank",
"Fortuneo",
"Groupama Banque",
"Hello Bank",
"HSBC France",
"HSBC France Pro",
"HSBC Entreprise (Elys PC)",
"HSBC Professionnel (Elys PC)",
"ING",
"La Banque Postale Particuliers",
"La Banque Postale Pro",
"LCL",
"LCL - e.LCL, 100% en ligne",
"LCL Entreprises et institutionnels",
"LCL Pro",
"Milleis",
"Monabanq",
"N26 (Number 26)",
"Natixis",
"Oney - Banque Accord",
"Oney Banque",
"Orange Bank",
"PayPal",
"Qonto",
"Revolut",
"Shine",
"Société Générale Entreprises",
"Société Générale Particuliers",
"Société Générale Pro",
"Société Marseillaise de Crédit",
"Unilend",
"Yomoni",
}