"use strict";
exports.__esModule = true;
var Transport;
(function (Transport) {
    Transport["Truck > 21 ton"] = "truck-diesel-21-more";
    Transport["Truck 19.1 at 21 ton"] = "truck-diesel-19_1-21_0";
    Transport["Truck 11 at 19 ton"] = "truck-diesel-11_0-19_0";
    Transport["Truck 6.1 at 10.9 ton"] = "truck-diesel-6_1-10_9";
    Transport["Truck 5.1 at 6 ton"] = "truck-diesel-5_1-6_0";
    Transport["Truck 3.6 at 5 ton"] = "truck-diesel-3_6-5_0";
    Transport["Truck diesel 2.6 at 3.5 ton"] = "truck-diesel-2_6-3_5";
    Transport["Truck gasoline 2.6 at 3.5 ton"] = "truck-gasoline-2_6-3_5";
    Transport["Truck diesel 1.6 at 2.5 ton"] = "truck-diesel-1_6-2_5";
    Transport["Truck gasoline 1.6 at 2.5 ton"] = "truck-gasoline-1_6-2_5";
    Transport["Truck diesel < 1.5 ton"] = "truck-diesel-1_5-less";
    Transport["Truck gasoline < 1.5 ton"] = "truck-gasoline-1_5-less";
    Transport["Van electric"] = "van-electric";
    Transport["Van diesel"] = "van-diesel";
    Transport["Van gasoline"] = "van-gasoline";
    Transport["Car electric"] = "car-electric";
    Transport["Car mixed moy"] = "car-mixed-moy";
    Transport["Car < 5 CV"] = "car-mixed-0_5";
    Transport["Car moy diesel"] = "car-diesel-moy";
    Transport["Car diesel > 11 CV"] = "car-diesel-11-more";
    Transport["Car diesel between 6 to 10 CV"] = "car-diesel-6_10";
    Transport["Car diesel < 5 CV"] = "car-diesel-0_5";
    Transport["Car moy gasoline"] = "car-gasoline-moy";
    Transport["Car gasoline > 11 CV"] = "car-gasoline-11-more";
    Transport["Car gasoline between 6 to 10 CV"] = "car-gasoline-6_10";
    Transport["Car gasoline < 5 CV"] = "car-gasoline-0_5";
    Transport["Moto > 750 cm3"] = "moto-750-more";
    Transport["Moto < 750 cm3"] = "moto-750-less";
    Transport["Bike"] = "bike";
    Transport["Passenger train"] = "train-passenger";
    Transport["TER France - Diesel"] = "ter-france-diesel";
    Transport["TER France - Electric"] = "ter-france-elec";
    Transport["Subway, city > 250 000 inhabitants"] = "subway-elec-2";
    Transport["Subway, city > 150 000 at 250 000 inhabitants"] = "subway-elec-1";
    Transport["Bus"] = "bus-diesel";
    Transport["Day ferry"] = "ferry-day";
    Transport["Night ferry"] = "ferry-night";
    Transport["Plane < 10000km"] = "plane-10000";
    Transport["Plane < 5000km"] = "plane-5000";
})(Transport = exports.Transport || (exports.Transport = {}));
