name: Publish

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.16.3
                  registry-url: https://registry.npmjs.org/
            - run: npm install
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    deploy-pages:
        runs-on: ubuntu-latest
        env:
          working-directory: documentation/website
        steps:
          - uses: actions/checkout@v1
            
          - uses: actions/setup-node@v1
            with:
                node-version: 12.16.3
                registry-url: https://registry.npmjs.org/
          - run : npm install
            working-directory: ${{env.working-directory}}
          - run : npm build
            working-directory: ${{env.working-directory}}
          - run : npm build
            working-directory: ${{env.working-directory}}
          - name: Deploy to GitHub Pages
            uses: JamesIves/github-pages-deploy-action@3.5.9
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages # The branch the action should deploy to.
              FOLDER: documentation/website/build 
